name: Digital Ocean Shiny Docker Deploy

on: [push]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/shiny-meta-analyzer
          cache_froms: docker.pkg.github.com/${{ github.repository }}/shiny-meta-analyzer:latest
          tags: latest
          tag_with_sha: true
    
      - name: Docker deploy
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: ${{ secrets.SERVER }}
          script: 'docker stop my-shiny; docker rm my-shiny; docker run -d -p 80:80 --name my-shiny docker.pkg.github.com/ricoms/shiny_meta_analyzer/shiny-meta-analyzer:latest'
          key: ${{ secrets.SSH_KEY }}
