name: Digital Ocean Shiny simple Deploy

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: ${{ secrets.SERVER }}
        script: 'cd /srv/shiny-server/Shiny_meta_analyzer/; git checkout master; git pull;'
        key: ${{ secrets.SSH_KEY }}