name: Digital Ocean Shiny simple Deploy

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: ${{ secrets.SERVER }}
        script: 'cd /srv/shiny-server/Shiny_meta_analyzer/; git checkout master; git pull;'
        key: ${{ secrets.SSH_KEY }}
  setup:
    name: App setup
    runs-on: ubuntu-18.04
    needs: build
    steps:
    - run: |
      export R_BASE_VERSION 4.0.1
      apt-get update \
      && apt-get install -t unstable -y --no-install-recommends \
        gcc-9-base \
        littler \
        r-cran-littler \
        r-base=${R_BASE_VERSION}-* \
        r-base-dev=${R_BASE_VERSION}-* \
        r-recommended=${R_BASE_VERSION}-* \
      && ln -s /usr/lib/R/site-library/littler/examples/install.r /usr/local/bin/install.r \
      && ln -s /usr/lib/R/site-library/littler/examples/install2.r /usr/local/bin/install2.r \
      && ln -s /usr/lib/R/site-library/littler/examples/installGithub.r /usr/local/bin/installGithub.r \
      && ln -s /usr/lib/R/site-library/littler/examples/testInstalled.r /usr/local/bin/testInstalled.r \
      && install.r docopt \
      && rm -rf /tmp/downloaded_packages/ /tmp/*.rds \
      && rm -rf /var/lib/apt/lists/*
      R -e "install.packages('plyr',dependencies=TRUE, repos='http://cran.rstudio.com/')"
      Rscript scripts/turnToBin.R 