name: Digital Ocean Shiny simple Deploy

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: ${{ secrets.SERVER }}
        script: 'cd /srv/shiny-server/Shiny_meta_analyzer/; git checkout master; git pull;'
        key: ${{ secrets.SSH_KEY }}
  setup:
    name: App setup
    runs-on: ubuntu-18.04
    needs: build
    steps:
    - name: Setup R
      uses: r-lib/actions/setup-R@v1
      with:
        r-version: '4.0.1'
    - run: R -e "install.packages('plyr',dependencies=TRUE, repos='http://cran.rstudio.com/')"
    - run: Rscript scripts/turnToBin.R 