name: Digital Ocean Shiny simple Deploy

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: ${{ secrets.SERVER }}
        script: scripts/deployment.sh
        key: ${{ secrets.SSH_KEY }}