name: Digital Ocean Shiny simple Deploy
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: build

    runs-on: ubuntu-18.04
    steps:
      - name: ssh to server and pull github repo
        run: |
          echo ${{ secrets.SERVER }}
          touch deployment.txt
          echo ${{ secrets.SSH_KEY }} > deployment.txt
          chmod 600 deployment_key.txt
          ssh -i deployment.txt root@${{ secrets.SERVER }} 'cd /srv/shiny-server/Shiny_meta_analyzer/; git checkout master; git pull;'